### ISSUE TITLE
Add support for Conqueror´s Blade (CB)

### ISSUE THREAD

**Issue by inquisicionrecluta** [GameTactic/Issues#36] opened 2021-11-06 12:57 UTC
Hi all,

First of all, I want to thank the creators of this tool, it is fantastic. I am part of a community of Conqueror's Blade players, and we have been using it for 2 years.

When we started using it, we connected to https://wottactics.com, there we created our tactics and uploaded the game maps by URL using the imgur.com service.

I don't remember exactly what happened, but one day we suddenly entered with our Steam account and all the tactics had been lost, we do not know the reason and it does not matter.

At that moment we felt the frustration of losing all the tactics we had been working on, but we were clear that we wanted to continue using it for all the advantages it has.

I made the decision to create our own fork of the project and try to understand it well enough to add "native" support for Conqueror's Blade.

The result is that I managed to start a simplified version, in which I only left the login activated through STEAM to create an account, and I also hid the combobox to select other games because for that people use the official version of the tool, and also for spending the minimum time to get the application working.

You can see the result here:

https://conquerorsblade.inquisicion.club/

If you look at the footer section of the home screen, the donation buttons are still linked to the Paypal / Patreon account of the original creator, it seemed fair to me in gratitude to the creators, while the cost of hosting (CX11 instance in Hetzner) It has been assuming by my home in CB

At first our version of wottactics was only used by us, but little by little it became known and other houses in the game began to use it, which is a personal satisfaction of mine for having created this version, but above all it is for you creators, in fact I have met several players did the same as us and used the official version uploading map images, but with this version they LOVED and continued playing in the game more time. 

Motivated by personal issues, it is possible that in a while he will stop being a active player and be more casual, but before that happens I have decided to at least ask you if you would find it interesting that the InquisicioN house (that's what we call ourselves in the game :-) contributes to the official version supports Conqueror's Blade.

If you find it interesting then you have me at your disposal to see how we could do it.

You have the code of our fork here:

https://github.com/inquisicionrecluta/wottactics

The quality of the maps in some cases is a bit sloppy, because they are "in-game" captures and names of the players participating in a 15vs15 siege appear, or some texts / names of css styles appear in Spanish, but all of them are Tweaks that could be refined, as well as some texts of unit names that appear in Spanish, as they could be translated into English, etc. definitely open to criticism.

Thanks in advance for your time, have a nice day.
Savage
P.D: INQUISICION RECLUTA

**Comment by NikoGrano** [comment] 2022-02-04 10:32
Closed as duplicate of #22

**Closed by NikoGrano** 2022-02-04 10:32 UTC
