### ISSUE TITLE
Unable to upload map background

### ISSUE THREAD

**Issue by philj76** [GameTactic/Issues#16] opened 2020-05-04 15:11 UTC
When using the upload background for the map, it gives the option to select a local file, but the image is never displayed.
Linking the same image from a wedsite does work however

**Comment by NikoGrano** [comment] 2020-05-04 15:23
Addressed in our blog post and discord server multiple times. Cannot be fixed.

**Closed by NikoGrano** 2020-05-04 15:23 UTC
Labels: bug

**Comment by philj76** [comment] 2020-05-04 15:44
Thanks for the feedback, I was not aware it was already addressed, sorry. Will this feature work in the new site you are working on?

**Comment by NikoGrano** [comment] 2020-05-04 15:45
I cannot confirm when it is going to be implemented, but I can confirm it is going to be a feature. Later or sooner.

**Comment by philj76** [comment] 2020-05-04 15:53
Apologies for replying in a closed thread, but is this the same for the icon upload as well? I have the same issue uploading a test icon and do not want to make a new issue for it.

**Comment by NikoGrano** [comment] 2020-05-12 21:11
@philj76 It was fixed and it included a lot of hacky stuff to fix it. For icons it would require even more hacky stuff which I'm not ready to do. For now you need to go without custom icons.

Once 10GB of maps have been uploaded they all will be automatically flushed without warning. So even this custom map is very not recommended.

**Comment by philj76** [comment] 2020-05-13 14:04
@NikoGrano
Thank you very much for your efforts. My aim for the icons was to test some things before asking the devs of Hell Let Loose if they could help provide anything and put in a request for HLL support on your site.

**Comment by NikoGrano** [comment] 2020-05-13 14:21
@philj76 I understand. It's just too much work without guarantee it would work or if it will break something new. I cannot take that risk for now. For new GameTactic we are considering something like that, but not for first releases.

**Comment by philj76** [comment] 2020-05-13 14:30
@NikoGrano Sure that is fine.
If a request is put in for a new game to support, i.e. HLL, would you need the games maps and any custom icons for it and they would be just apart of that game selection much like how WOT is now?

**Comment by bryansamuel1** [comment] 2020-05-13 14:41
@philj76 we would need icons that would uniquely represent the "things" that you use in your tactics. For WoWs you have ships and WoTs you have tanks. I don't know your game but if you can identify the  characters, "things" or entities that you would want to build tactics with, we will need icons for those. For CSGO for example we also have soldier icons but additional icons that represent their weapon loadout. The decision is up to you and your gaming community.

Right now there is no rush to go getting any of these icons because we aren't in a position to develop any new games for a while, but it is a good idea for you to think about how you use wottactics.com and what we could do it to make it much much better for you!
